name: Black Duck SCA Test

# Controls when the workflow will run
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #  runs-on: [ ubuntu-latest ]
    # runs-on: [ self-hosted ]
    # Use ubuntu-latest to run workflow on github hosted runner
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v3

      - name:   Black Duck SCA Scan
        # if: ${{ github.event_name != 'pull_request' }}
        # Use the action defined in this repository
        uses: blackduck-inc/black-duck-security-scan@SIGINT-2423
        with:
          blackduck_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackduck_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_reports_sarif_create: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
